### ISSUE TITLE
URLs that contain a port number are not supported.

### ISSUE THREAD

**Issue by mglaman** [json-api/explorer#8]
Given a URL with a port, such as `http://127.0.0.1:8080/jsonapi/explorer/app?location=http://127.0.0.1:8080`, the app crashes.

It ends up appending the port on subsequent URL builds.

<img width="1053" alt="Screen Shot 2019-10-31 at 3 20 57 PM" src="https://user-images.githubusercontent.com/3698644/67983218-3fa5d200-fbf2-11e9-9566-560c5477c35d.png">

**Comment by zrpnr** [comment]
I think that's from `compileJsonApiUrl` in src/lib/url/url.js
The port was added in separately there, let me know if that fixes it for you.

**Comment by mglaman** [comment]
<img width="1258" alt="Screen Shot 2019-10-31 at 5 00 44 PM" src="https://user-images.githubusercontent.com/3698644/67989189-01afaa80-fc00-11e9-98cd-667b3f900af4.png">

it works, thank you!
